[project]
name = "cupcake-kata"
version = "0.1.0"
description = "A kata for practicing Decorator and Composite design patterns with cupcakes"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=7.0.0",
]
